<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog_productos[
    <!ELEMENT catalog_productos (producto+)>
    <!ELEMENT producto (caracteristicas)>
    <!ATTLIST producto nombre CDATA #REQUIRED>
    <!ATTLIST producto precio CDATA #REQUIRED>
    <!ATTLIST producto descripcion CDATA #REQUIRED>
    <!ELEMENT caracteristicas (caracteristica+)>
    <!ELEMENT caracteristica (EMPTY)>
    <!ATTLIST caracteristica id NMTOKEN #REQUIRED>
    <!ATTLIST caracteristica valor CDATA #REQUIRED>
]>
<catalog_productos>
    <producto nombre="Iphone-11" precio="293€" descripcion="descripcon">
        <caracteristicas>
            <caracteristica id="1" valor="valor1"></caracteristica>
            <caracteristica id="1" valor="valor1"></caracteristica>
        </caracteristicas>
    </producto>
    <producto nombre="Iphone-14" precio="2857€" descripcion="descripcion">
        <caracteristicas>
            <caracteristica id="1" valor="valor1"></caracteristica>
            <caracteristica id="1" valor="valor1"></caracteristica>
        </caracteristicas>
    </producto>
</catalog_productos>